# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: warehouse.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fwarehouse.proto\x12\twarehouse\"|\n\x0bProductData\x12\x11\n\tproductID\x18\x01 \x01(\t\x12\x13\n\x0bproductName\x18\x02 \x01(\t\x12\x17\n\x0fproductCategory\x18\x03 \x01(\t\x12\x17\n\x0fproductQuantity\x18\x04 \x01(\x05\x12\x13\n\x0bproductUnit\x18\x05 \x01(\t\"\xe3\x01\n\rWarehouseData\x12\x13\n\x0bwarehouseID\x18\x01 \x01(\t\x12\x15\n\rwarehouseName\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x18\n\x10warehouseAddress\x18\x04 \x01(\t\x12\x1b\n\x13warehousePostalCode\x18\x05 \x01(\x05\x12\x15\n\rwarehouseCity\x18\x06 \x01(\t\x12\x18\n\x10warehouseCountry\x18\x07 \x01(\t\x12+\n\x0bproductData\x18\x08 \x03(\x0b\x32\x16.warehouse.ProductData\"\'\n\x0fMessageResponse\x12\x14\n\x0cresponseData\x18\x01 \x01(\t2X\n\tWarehouse\x12K\n\x11GetServerResponse\x12\x18.warehouse.WarehouseData\x1a\x1a.warehouse.MessageResponse\"\x00\x42\x13\n\x11io.grpc.warehouseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'warehouse_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021io.grpc.warehouse'
  _globals['_PRODUCTDATA']._serialized_start=30
  _globals['_PRODUCTDATA']._serialized_end=154
  _globals['_WAREHOUSEDATA']._serialized_start=157
  _globals['_WAREHOUSEDATA']._serialized_end=384
  _globals['_MESSAGERESPONSE']._serialized_start=386
  _globals['_MESSAGERESPONSE']._serialized_end=425
  _globals['_WAREHOUSE']._serialized_start=427
  _globals['_WAREHOUSE']._serialized_end=515
# @@protoc_insertion_point(module_scope)
